<?xml version="1.0"?>
<package format="2">
  <name>mowen_navigation</name>
  <version>0.0.1</version>
  <description>ROS1 move_base navigation config for mowen mecanum wheel robot</description>
  <maintainer email="user@example.com">user</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>move_base</depend>
  <depend>amcl</depend>
  <depend>map_server</depend>
  <depend>dwa_local_planner</depend>
  <depend>navfn</depend>
  <depend>costmap_2d</depend>
  <depend>rotate_recovery</depend>
  <depend>clear_costmap_recovery</depend>

  <export>
    <build_type>catkin</build_type>
  </export>
</package>
