<?xml version="1.0"?>
<package format="2">
  <name>mowen_cartographer</name>
  <version>1.0.0</version>
  <description>Cartographer SLAM for Mowen robot</description>
  <maintainer email="your@email.com">Your Name</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>

  <exec_depend>cartographer_ros</exec_depend>

  <export>
    <build_type>catkin</build_type>
  </export>
</package>
